
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;

	private global::Gtk.Label headlineLbl;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label4;

	private global::Gtk.Entry primeTxt;

	private global::Gtk.Button button1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label6;

	private global::Gtk.Image isPrimeResultImg;

	private global::Gtk.Label firstFactorLbl1;

	private global::Gtk.Label firstFactorLbl;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.headlineLbl = new global::Gtk.Label();
		this.headlineLbl.Name = "headlineLbl";
		this.headlineLbl.LabelProp = global::Mono.Unix.Catalog.GetString("Prime checker");
		this.headlineLbl.UseMarkup = true;
		this.vbox4.Add(this.headlineLbl);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.headlineLbl]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 150;
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Primenumber:");
		this.hbox3.Add(this.label4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.primeTxt = new global::Gtk.Entry();
		this.primeTxt.WidthRequest = 150;
		this.primeTxt.CanFocus = true;
		this.primeTxt.Name = "primeTxt";
		this.primeTxt.IsEditable = true;
		this.primeTxt.InvisibleChar = '•';
		this.hbox3.Add(this.primeTxt);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.primeTxt]));
		w3.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 150;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Evaluate");
		this.hbox3.Add(this.button1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(4));
		this.vbox4.Add(this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.WidthRequest = 150;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("isPrime");
		this.hbox4.Add(this.label6);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label6]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.isPrimeResultImg = new global::Gtk.Image();
		this.isPrimeResultImg.Name = "isPrimeResultImg";
		this.isPrimeResultImg.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Menu);
		this.hbox4.Add(this.isPrimeResultImg);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.isPrimeResultImg]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.firstFactorLbl1 = new global::Gtk.Label();
		this.firstFactorLbl1.Name = "firstFactorLbl1";
		this.firstFactorLbl1.LabelProp = global::Mono.Unix.Catalog.GetString("firstFactor");
		this.hbox4.Add(this.firstFactorLbl1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.firstFactorLbl1]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.firstFactorLbl = new global::Gtk.Label();
		this.firstFactorLbl.WidthRequest = 150;
		this.firstFactorLbl.Name = "firstFactorLbl";
		this.hbox4.Add(this.firstFactorLbl);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.firstFactorLbl]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox4.Add(this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.Add(this.vbox4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1182;
		this.DefaultHeight = 495;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.checkIsPrime);
	}
}
